services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - connectsphere-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - SUI_NETWORK=testnet
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:3000
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - connectsphere-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - connectsphere-network

volumes:
  redis_data:

networks:
  connectsphere-network:
    driver: bridge
